export default{
	state:{
		list:[{
			name:'张三丰',
			tel:'13234324324',
			city:"清宁省和海市鼓楼街花滨路",
			details:'2号楼',
			isDefault:false
		},{
			name:'李四',
			tel:'283238293',
			city:"清宁省和海楼街花滨路",
			details:'3号楼',
			isDefault:true
		},{
			name:'大刀王',
			tel:'039393939',
			city:"清宁省和海市花滨路",
			details:'4号楼',
			isDefault:false
		}]
	},
	getters:{
		defaultPath(state){
			return state.list.filter(v=>v.isDefault)
		}
	},
	mutations:{
		createPath(state,obj){
			state.list.unshift(obj)
		},
		updatePath(state,{index,item}){
			for(let key in item){
				state.list[index][key]=item[key];
			}
		},
		removePath(state){
			state.list.forEach(v=>{
				if(v.isDefault){
					v.isDefault=false
				}
			})
		}
	},
	actions:{
		createPathFn({commit},obj){
			if(obj.isDefault){
				commit('removePath')
			}
			commit('createPath',obj)
		},
		updatePathFn({commit},obj){
			if(obj.item.isDefault){
				commit('removePath')
			}
			commit('updatePath',obj)
		}
	}
}